#!/bin/bash
SQL="INSERT INTO cloud4.banned_domain (domain, language) VALUES('$1', 'manual');"
echo $SQL
cqlsh -e "$SQL"
SQL="SELECT * FROM cloud4.banned_domain WHERE domain = '$1';"
cqlsh -e "$SQL"

echo $1 >> /home/spider/data/0-banned-domains.txt
tail -10 /home/spider/data/0-banned-domains.txt

grep -lir "$1" /home/spider/data/
sed -i "/$1/d;" /home/spider/data/1-friendly-domains.txt
